version: "2.9"
services:
  novnc:
    container_name: novnc
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=600
      - DISPLAY_HEIGHT=1024
      - RUN_XTERM=no
      - RUN_FLUXBOX=no
    ports:
      - "8080:8080"
    networks:
      - x11

  monitor:
    container_name: monitor
    depends_on:
      - novnc
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    networks:
      - x11
    environment:
      - DISPLAY=novnc:0.0
      - SDL_VIDEODRIVER=x11
      - SDL_NOMOUSE=1
      - SNAP=/app
      - SNAP_DATA=/app/monitor/logs
      - SNAP_COMMON=/app/instance
      - ID=${ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}

networks:
  x11: