---
version: "3.9"
services:
  rmq:
    container_name: rmq
    image: ghcr.io/incuvers/rabbitmq:arm64
    ports:
      # expose for rmq management client
      - "15672:15672"
    networks:
      - amqp

  novnc:
    container_name: novnc
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=576
      - DISPLAY_HEIGHT=1024
      - RUN_XTERM=no
      - RUN_FLUXBOX=no
    ports:
      - "8080:8080"
    networks:
      - x11

  monitor:
    container_name: monitor
    depends_on:
      - rmq
      - novnc
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    networks:
      - x11
      - amqp
    environment:
      - DISPLAY=novnc:0.0
      - SDL_VIDEODRIVER=x11
      - SDL_NOMOUSE=1
      - MPLBACKEND=Agg
      - COMMON=/app/instance
      - MONITOR_LOGS=/app/instance/logs
      - MONITOR_CACHE=/app/instance/cache
      - MONITOR_CERTS=/app/instance/certs
      - MONITOR_DPC=/app/instance/dpc
      - MONITOR_ENV=development
      - RABBITMQ_ADDR=rmq:5672
      - API_BASE_URL=https://api.dev.incuvers.com
      - API_BASE_PATH=/v1

networks:
  x11:
  amqp:
