---
version: "2.9"
services:
  rmq:
    container_name: rmq
    image: rabbitmq:3.9-management
    volumes:
      - "../rabbitmq/:/etc/rabbitmq/"
    ports:
      # expose for rmq web client
      - "15672:15672"

  novnc:
    container_name: novnc
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=600
      - DISPLAY_HEIGHT=1024
      - RUN_XTERM=no
      - RUN_FLUXBOX=no
    ports:
      - "8080:8080"
    networks:
      - x11

  monitor:
    container_name: monitor
    depends_on:
      - rmq
      - novnc
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    networks:
      - x11
    environment:
      - ID=${ID}
      - DISPLAY=novnc:0.0
      - SDL_VIDEODRIVER=x11
      - SDL_NOMOUSE=1
      - SNAP=/app
      - SNAP_DATA=/app/monitor/logs
      - SNAP_COMMON=/app/instance
      - MPLBACKEND=Agg
      - MONITOR_CACHE=/app/instance/cache
      - MONITOR_MODE=monitor
      - MONITOR_ENV=development
      - RABBITMQ_ADDR=rmq:5672
      - API_BASE_URL=https://api.dev.incuvers.com
      - API_BASE_PATH=/v1

networks:
  x11:
