---
network:
  version: 2
  renderer: NetworkManager
  wifis:
    wlan0:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 50
      access-points:
        "IO_PORTFOLIO":
          password: "K6FdxP027"
