---
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eth0:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
  wifis:
    wlan0:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 50
      access-points:
        SSID:
          password: "ssid_password"
