---
name: ci
on:
  push:
    branches:
      - master
  pull_request:
    type: [opened, synchronized, re-opened]
    branches:
      - master

jobs:
  unittest:
    name: unittest suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Install dependancies
        run: |
          apt update
          xargs -a apt-packages.txt sudo apt install -y
          python3 -m pip install freezegun
          python3 -m pip install -r requirements.txt
      - name: Run unittest suite
        run: make unit
  lint:
    name: lint suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Install dependancies
        run: |
          apt update
          xargs -a apt-packages.txt sudo apt install -y
          python3 -m pip install flake8
          python3 -m pip install -r requirements.txt
          touch .env
      - name: Run lint directive
        run: make lint
  pip:
    name: pip package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install monitor
        run: |
          apt update
          xargs -a apt-packages.txt sudo apt install -y
          python3 -m pip install .
          python3 -c 'import monitor; print(monitor.__version__)'
